export const MODAL_TYPES = {
  SHOW_MODAL: 'MODAL_TYPES.SHOW_MODAL',
  HIDE_MODAL: 'MODAL_TYPES.HIDE_MODAL',
  STORE_MODAL: 'MODAL_TYPES.STORE_MODAL',
  UNSTORE_MODAL: 'MODAL_TYPES.UNSTORE_MODAL',
  MODAL_IS_HIDING: 'MODAL_TYPES.MODAL_IS_HIDING',
};
