export const APP_TYPES = {
  GET_CONTEST_INFO_REQUEST: 'HOME_PAGE_TYPES.GET_CONTEST_INFO_REQUEST',
  GET_CONTEST_INFO_SUCCESS: 'HOME_PAGE_TYPES.CONTEST_INFO_SUCCESS',
  GET_CONTEST_INFO_FAIL: 'HOME_PAGE_TYPES.GET_CONTEST_INFO_FAIL',
};
