export const FORM_PAGE_TYPES = {
  POST_FORM_REQUEST: 'FORM_PAGE_TYPES.POST_FORM_REQUEST',
  POST_FORM_SUCCESS: 'FORM_PAGE_TYPES.POST_FORM_SUCCESS',
  POST_FORM_FAIL: 'FORM_PAGE_TYPES.POST_FORM_FAIL',

  GET_FORM_INFO_REQUEST: 'FORM_PAGE_TYPES.GET_FORM_INFO_REQUEST',
  GET_FORM_INFO_SUCCESS: 'FORM_PAGE_TYPES.GET_FORM_INFO_SUCCESS',
  GET_FORM_INFO_FAIL: 'FORM_PAGE_TYPES.GET_FORM_INFO_FAIL',
};
