export const FORM_PAGE_TYPES = {
  POST_FORM_REQUEST: 'FORM_PAGE_TYPES.POST_FORM_REQUEST',
  POST_FORM_SUCCESS: 'FORM_PAGE_TYPES.POST_FORM_SUCCESS',
  POST_FORM_FAIL: 'FORM_PAGE_TYPES.POST_FORM_FAIL',
};
