export const USER_TYPES = {
  SET_TOKEN: 'USER_TYPES.SET_TOKEN',
  SET_USER_DATA: 'USER_TYPES.SET_USER_DATA',
  SET_TOKEN_FAIL: 'USER_TYPES.SET_TOKEN_FAIL',

  GET_CONTESTS_REQUEST: 'USER_TYPES.GET_CONTESTS_REQUEST',
  GET_CONTESTS_SUCCESS: 'USER_TYPES.GET_CONTESTS_SUCCESS',
  GET_CONTESTS_FAIL: 'USER_TYPES.GET_CONTESTS_FAIL',
};
