export const LEADERBOARD_PAGE_TYPES = {
  GET_LEADERBOARD_LIST_REQUEST: 'LEADERBOARD_PAGE_TYPES.GET_LEADERBOARD_LIST_REQUEST',
  GET_LEADERBOARD_LIST_SUCCESS: 'LEADERBOARD_PAGE_TYPES.GET_LEADERBOARD_LIST_SUCCESS',
  GET_LEADERBOARD_LIST_FAIL: 'LEADERBOARD_PAGE_TYPES.GET_LEADERBOARD_LIST_FAIL',
  SET_SEARCH_SUCCESS: 'LEADERBOARD_PAGE_TYPES.SET_SEARCH_SUCCESS',
};
